config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("stats.urls", namespace="stats"))
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

stats/urls.py
from django.urls import path
from stats import views

app_name = "stats"
urlpatterns = [
    path('', views.StatisticListView.as_view(), name="statistics"),
    path('create', views.StatisticCreateView.as_view(), name="statistic_add"),
    path('<slug>', views.Dashboard.as_view(), name="dashboard"),

]

stats/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

class Statistic(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(blank=True)

    def get_absolute_url(self):
        return reverse("stats:dashboard", kwargs={'slug': self.slug})

    @property
    def data(self):
        return self.items.all()
    
    def __str__(self):
        return str(self.name)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)



class DataItem(models.Model):
    statistic = models.ForeignKey(Statistic, on_delete=models.CASCADE, related_name="items")
    value = models.PositiveSmallIntegerField()
    owner = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.owner}: {self.value}"

stats/views.py
from typing import Any
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from stats.models import (Statistic, DataItem)


class StatisticListView(generic.ListView):
    model = Statistic
    template_name = 'stats/main.html'
    queryset = Statistic.objects.all()
    context_object_name = 'statistics'    


class StatisticCreateView(generic.CreateView):
    model = Statistic
    fields = ['name']
    success_url = reverse_lazy('stats:statistics')
    template_name = 'stats/main.html'
    

class Dashboard(generic.DetailView):
    template_name = 'stats/dashboard.html'
    model = Statistic
    context_object_name = 'statistic'

stats/templates/stats/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<a href="{% url 'stats:statistics' %}">Voltar</a>
<h1> Dashboard: {{ statistic.name }}</h1>
{% endblock %}

{% block js %}
<script src="{% static 'stats/dashboard.js' %}" defer></script>
{% endblock %}

stats/templates/stats/main.html
{% extends 'base.html' %}

{% block content %}
    <h1> Statistics </h1>

    <form  method="POST" action="{% url 'stats:statistic_add' %}">
        {% csrf_token %}

        <input type="text" id="id_name" name="name" placeholder="">
        <button>Adicionar</button>
    </form>

    {% if statistics %}
        <ul>
            {% for statistic in statistics %}
                <li>
                    <a href="{{ statistic.get_absolute_url }}">
                        {{ statistic.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>


    {% endif %}

{% endblock %}

{% block js %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Django Channels
    </title>

    
</head>
<body>
    <div class="containter">
        {% block content %}
        {% endblock %}
    </div>

    {% block js %}
    {% endblock %}
</body>
</html>